### ISSUE TITLE
[SUG] Make WebServices optional

### ISSUE THREAD

**Issue by Unknown-User2** [TudbuT/ttc#10]
**Describe the solution you'd like**
When you start the client for the first time ask the user if they'd like to be tracked by WebServices

**Comment by Unknown-User2** [comment]
I don't need it i removed it myself [https://github.com/Unknown-User2/ttc](https://github.com/Unknown-User2/ttc)

**Comment by TudbuT** [comment]
Well the reason WebServices exist is mainly so that I can flex how many people actively use TTC, so I wouldn't want to do this. 
Of course, I will allow your fork because it does not remove credits.
