### ISSUE TITLE
Fix the fucking GUI

### ISSUE THREAD

**Issue by FaxHack** [TudbuT/ttc#3]
so yes the gui is trash pls fix it when u click on it it closes i will try fix that but yes fuck it ur self ig

**Comment by FaxHack** [comment]
unban me from server to maybe FaxHack#1211

**Comment by WooHooASDF** [comment]
That doesn’t happen with anyone else I know, can you provide a more detailed .explanation? Of the GUI crash, that is

**Comment by TudbuT** [comment]
Fix your grammar and your insults, then I'll fix your nonexistent issue. Thanks!

**Comment by master7720** [comment]
> That doesn’t happen with anyone else I know, can you provide a more detailed .explanation? Of the GUI crash, that is

there is no crash the gui is just very bad

**Comment by FaxHack** [comment]
> > That doesn’t happen with anyone else I know, can you provide a more detailed .explanation? Of the GUI crash, that is
> 
> 
> 
> there is no crash the gui is just very bad

Make a new on then

**Comment by master7720** [comment]
> > > That doesn’t happen with anyone else I know, can you provide a more detailed .explanation? Of the GUI crash, that is
> > 
> > 
> > there is no crash the gui is just very bad
> 
> Make a new on then

i would but i aint a dev for this client
