### ISSUE TITLE
[BUG] God please fix this (every single outdated version)

### ISSUE THREAD

**Issue by AcaiBerii** [TudbuT/ttc#5]
**Describe the bug**
A clear and concise description of what the bug is:

**To Reproduce**
1. Go to the Minecraft launcher
2. Open an outdated version of TTC
3. Go in a singleplayer or multiplayer game
4. Die

**Expected behavior**
I expected not to be constantly annoyed about updating a garbage client.

**Screenshots**
https://i.imgur.com/Ute1REn.png

**Desktop (please complete the following information):**
 - OS: Window ten
 - Browser chome
 - Version EVERY ONE

**Additional context**
HHHHHHHHHHHHH

**Comment by TudbuT** [comment]
Ok i will disable the message
