### ISSUE TITLE
Crashes when loading mod

### ISSUE THREAD

**Issue by oClown** [TudbuT/ttc#6]
if you dont know how to fix this i'll try and figure it out myself.
crash log file:
[crash-2021-06-21_00.18.26-client.txt](https://github.com/TudbuT/ttc/files/6683245/crash-2021-06-21_00.18.26-client.txt)

**Comment by WooHooASDF** [comment]
Please check the discord, help can be offered more easily there.

**Comment by oClown** [comment]
kk ty

**Comment by TudbuT** [comment]
Can't reproduce. Please delete your config and try again
